### ISSUE TITLE
User can connect to login server even if already connected

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#114]
I noticed that users can connect to the login server even if the account they use is already connected.

It should be fixed asap before opening the test server.

**Comment by johmarjac** [comment]
Wooop, I thought you already were aware of that long time ago. I knew it already xD

**Comment by Eastrall** [comment]
@johmarjac Yes, I was aware of this bug. I opened this issue to not forget to fix this before opening the test server 😄 
Plus, if someone wants to fix it, the issue is here to follow the process.

**Comment by johmarjac** [comment]
Aight, I spent some thoughts about that, and I am not entirely sure what we need to take care of.
First of all problems is, that if the client is already in the cluster or world server, we cannot track someone from login server only. So we have to actually query all clusters, get the current players account name and see if it's equal to the one just logging in. What do you think? Or is there an even better way?

**Comment by Eastrall** [comment]
After some tests, I've been able to check if the user is already connected to the login server. If it is already connected, we have to send the following error: `DUPLICATE_ACCOUNT`. This error will tell the client that the account is already connected and will ask him if he wants to close the existing connection. 
If we clicks the yes button, the `PACKETTYPE_CLOSE_EXISTING_CONNECTION` (0x16) packet is sent to the server to close the other connection.
