### ISSUE TITLE
Inter-Server-Communication system

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#167]
Servers need to communicate with each other in order to send data across multiple channels (broadcast) and to be known from the Login Server that will send the available server's list to the players.
The actual system is kinda messy because at the begining of the project we needed to send data quickly, so **I** made things quite dirty, and I apologize.

Today let's talk about this to refactor this system and make it easier to use and in compliance with the actual architecture.

Actually, the "Core Server" is located inside the `LoginServer`. So every server connects to the LoginServer and is identified with an unique ID.
We need to change this architecture so the `WorldSever`s connect to its `ClusterServer` and the `ClusterServer`s connects to the main `LoginServer`.

This will allow a better broadcast management and separation of concerns.

My thoughts is that the client wrapper (client that connects either to the login or cluster) needs to have an interface (let's say: `IClusteClient` for world -> cluster or `ILoginClient` for cluster -> login). With this, we can easily register this "core client" into the `DependencyContainer` as a Singleton and retrieve it whenever we want to.

For example, in the mail system on the `WorldServer, we could do something like:

```csharp
public void On....()
{
    var clusterClient = DependencyContainer.Instance.Resolve<IClusterClient>();

    using (var packet = new NetPacket()) // using ether.network default packet handler
    {
         packet.Write(...);
         clusterClient.Send(packet); // Sending the packet to the cluster server
    }
}
```

Then on the cluster server we receive the packet and we broadcast the same message to every connected servers:
```csharp
public override HandleMessage(INetPacketStream packet)
{
    foreach (var world in this._worldServers)
         world.Send(...);
}
```

And for receiving data from the ClusterClient :
```csharp
public class ClusterClient: NetClient, ICoreClient // NetClient from Ether.Network
{
     public override HandleMessage(INetPacketStream packet)
     {
         var header = packet.Read<int>(); // packet header
         switch (header)
         {
               case 0x01: // Assuming of course...
                     var playerId = packet.Read<int>();
                     var worldServer = DependencyContainer.Instance.Resolve<IWorldServer>();
                     var playerEntity = worldServer.GetPlayerEntityById(playerId);

                     playerEntity.NotifySystem<MailSystem>(...);
                     break;
         }
     }
}
```

Since we are in the server's context, we can easily retrieve data from the world server by resolving it from the DependencyContainer and notify a system. 😄 

What do you think about this idea ?

**Comment by johmarjac** [comment]
I think that is great, being able to notify the according system that there comes data from anothe channel.
But I dont like the part, that the message goes to every world server alltho it actually is relevant for only one World Server. So maybe we can think about some kind of additional flag telling which server is the message for and only sending it to the belonging server. 
Sending every message to every world server is not just an overhead of network traffic in the ISC but also more processing for the world server because he needs to actually process the message and see if its actually relevant...Lets say we have 3 WorldServers because of 3 Channels in a Cluster and a mail goes from Channel 1 to Channel 2, then its a waste of cpu and traffic on 2/3 servers

**Comment by Eastrall** [comment]
It will depend of the system. Let's say you want to notify only the player that is on world server 2, you will compose your packet so the cluster server sends broadcast the packet to the world server you want.

**Comment by johmarjac** [comment]
Okay yes, that would be just fine then 👍
