### ISSUE TITLE
where is the  bin/config ?  I have looked this "Edit the files in bin/config/ (login.json, cluster.json, world.json)" but I can't find config directory

### ISSUE THREAD

**Issue by swpuzhang** [Eastrall/Rhisis#195]

**Comment by Eastrall** [comment]
Hi,

Thank you for opening an issue.
You pointed a good problem. Documentation is not up to date!
To solve your problem, you will need install the .NET Core SDK and compile the entire solution using the following command:
```
$> dotnet build
```
Once the solution is built, go to the `bin/` folder and run the following command:
```
$> ./rhisis-cli.bat setup
```
This command will help you configure your Login, Cluster, World server, and configure the database access. 

You can check the Rhisis CLI available commands here: https://github.com/Eastrall/Rhisis/issues/184

I hope it helps you solve your issue. I mark this issue a documentation issue to remind me to update the documentation with the correct CLI commands to run.

**Comment by swpuzhang** [comment]
thank you

**Comment by Eastrall** [comment]
Reopening to keep a track of this issue and what to do next. 😉

**Comment by Eastrall** [comment]
I have updated the documentation for setting up the server on a debian environment : https://github.com/Eastrall/Rhisis/wiki/Setup-Rhisis-on-Debian-9#server-configuration
