### ISSUE TITLE
NPC dialog script

### ISSUE THREAD

**Issue by Anjuts** [Eastrall/Rhisis#211]
Please implement the next button on "introText". thanks. also if possible the level checker and job checker on a script.

**Comment by Eastrall** [comment]
In what case do you need to add a level checker and job checker ?
I think it is only used for quests, and quest scripts and dialogs are loaded directly through the official resources files.

**Comment by Anjuts** [comment]
I see. coz I use different level in official flyff. and it's a different conversation with npcs.

**Comment by Eastrall** [comment]
Solved in PR #215.
