### ISSUE TITLE
Inventory System

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#24]
The inventory system manages all the inventory actions such as the item creation, item moves/switch, equip/unequip.

- [x] Initialize inventory
- [x] Move items
- [x] Create items
- [x] Equip items (drag n drop on character)
- [x] Unequip items
- [x] Use items (7c081fc, 4477700, c3daa53)
- [x] Use equip items (equip when clicking) (7ade7fa)

**Comment by CineXMike** [comment]
@Eastrall What will be the item count limit?
So how many spots will there be maximum?

**Comment by johmarjac** [comment]
@CineXMike Do you mean the max inventory item count? Afaik this is limited to a constant value on the client side in the source which would require to modify the client executable heavily. But I am sure it is in @Eastrall interest to be able to have as much items as you want from the server side. So in case you fix your client to be able to handle X max items in your inventory, the server should be already able to handle that.

**Comment by Eastrall** [comment]
@johmarjac is right. The inventory system, bank account and extra bag are based on the [ItemContainerComponent](https://github.com/Eastrall/Rhisis/blob/develop/src/Rhisis.World/Game/Components/ItemContainerComponent.cs) in which you can specify the maximum size of your container. (see contructor).

As for the inventory system it self, size values are hardcoded in the server, but we can make them dynamic by creating a configuration entry in `world.json`.

**Comment by johmarjac** [comment]
@Eastrall Should the entry be naked inside world.json or would you prefer wrapping it in some kind of InventoryConfiguration class?

**Comment by Eastrall** [comment]
It has to be wrapped into a `InventoryConfiguration` section for readability. Something like:
```json
{
  "host": "127.0.0.1",
  ...
  "inventory": {
    "size": 73,
    "equipementOffset": 42"
    ...
  }
}
```

**Comment by CineXMike** [comment]
@johmarjac @Eastrall  Thanks for this explanation!

**Comment by johmarjac** [comment]
@CineXMike You´re welcome. 
@Eastrall Maybe I find some time implementing this. Shouldn´t be too much time consuming.

**Comment by Eastrall** [comment]
@johmarjac Feel free to make a PR with this feature. 😄
