### ISSUE TITLE
Item not removed when quantity reaches 0

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#256]
Thank you Xerta for reporting this issue.

## Description

When using a food item, and the quantity reaches 0, the item is not removed from the inventory.

![image](https://user-images.githubusercontent.com/4021025/60395949-60bebf00-9b3b-11e9-93d7-760fbfc3bfb5.png)

**Comment by MypowerHD** [comment]
When I am at home I can fix that. I've found it on the UseItem Logic, iam right that quantity -1 is for Items that haven't an Quantity?

**Comment by Eastrall** [comment]
You can only use an item that has the `IsUseable` flag set to `true`. For example, you can't use a `Wooden Sword`, but you can use a `Blinkwing` or a `Cookie`.
Check out the `InventoryItemUsage.cs` file and the `DecreaseItem()` method here: https://github.com/Eastrall/Rhisis/blob/develop/src/Rhisis.World/Systems/Inventory/InventoryItemUsage.cs#L91

**Comment by MypowerHD** [comment]
Ahh sorry, I check it out when iam at home, maby it's an issue with the reset function.
But later I can say more about that :)

**Comment by Eastrall** [comment]
This should be fixed with PR #278
