### ISSUE TITLE
CoreConfiguration will not Applyed

### ISSUE THREAD

**Issue by MypowerHD** [Eastrall/Rhisis#264]
There is an Issue with the section?
when i add the section mannualy into the json(after auto generate) it will work...

![image](https://user-images.githubusercontent.com/10728025/64135712-a7ef5780-cdeb-11e9-8036-996f1a1a7d49.png)

![image](https://user-images.githubusercontent.com/10728025/64136151-fb63a480-cdef-11e9-8b81-fc70741ded87.png)

https://github.com/Eastrall/Rhisis/blob/7e057933cedbf8f8f93e536dc2f01061c55041d0/src/Rhisis.Core/Structures/Configuration/ClusterConfiguration.cs#L15

**Comment by MypowerHD** [comment]
![image](https://user-images.githubusercontent.com/10728025/64136500-45e62080-cdf2-11e9-8995-25fc2cfc28bd.png)
https://github.com/Eastrall/Rhisis/blob/7e057933cedbf8f8f93e536dc2f01061c55041d0/src/Rhisis.Cluster/ClusterServerService.cs#L32

**Comment by Eastrall** [comment]
Thank you for reporting the issue. I have changed to way configuration files are loaded and I'm working on the CLI commands that generates the configuration files.

In order to resolve this issue, you should add the following in your JSON:

```json
{
    "clusterServer": {
        // Add all cluster configuration here
    },
    "isc": {
        "host": "",
        "port": 0,
        "password": ""
    }
}
```

The same goes for the the `LoginServer` which will have the `loginServer` key and the `WorldServer` will have the `worldServer` key.

**Comment by MypowerHD** [comment]
Can You send me A Valid world.json?

**Comment by MypowerHD** [comment]
Maby were add Newtonsoft.Json, for better Serialization and Deserialazation I have there an idea for the cli, when iam today at home I can set me on that and can rework it

**Comment by Eastrall** [comment]
The CLI is already in rework in this branch: [`fix/cli`](https://github.com/Eastrall/Rhisis/tree/fix/cli), and we do use Newtonsoft.Json.

The changes I've made on the branch are not stable yet, so I can't merge the changes on the `develop` branch yet.
If you want, I can give you some valid configuration files to test.

**Comment by MypowerHD** [comment]
Ahh OK, I didn't see that branch🙈

**Comment by Eastrall** [comment]
CLI tool has been improved and merged to `develop` branch. I strongly suggest you to run the following commands to configure Rhisis again:
```
$ ./rhisis-cli.bat configure login
$ ./rhisis-cli.bat configure cluster
$ ./rhisis-cli.bat configure world
```
