### ISSUE TITLE
WorldServer Configuration not fully Applyed

### ISSUE THREAD

**Issue by MypowerHD** [Eastrall/Rhisis#267]
![image](https://user-images.githubusercontent.com/10728025/64299768-a99b5580-cf7a-11e9-952b-1a3b4441bf9a.png)

When we configure the WorldServer with no configuration before, the configuration wont Apply Maps and ISC settings in the "worldServer" object. 

To fix that i try this fix, but nothing changed?
![image](https://user-images.githubusercontent.com/10728025/64299760-a56f3800-cf7a-11e9-8528-62be1bbb5df2.png)

**Comment by Eastrall** [comment]
It seems that the `WorldConfiguration` has the `isc` field is in too much.
https://github.com/Eastrall/Rhisis/blob/develop/src/Rhisis.Core/Structures/Configuration/World/WorldConfiguration.cs#L85

I'll remove it. Thanks for the feedback.

**Comment by Eastrall** [comment]
It should be fixed with #268.
