### ISSUE TITLE
Inventory System Bug with EquipItem()

### ISSUE THREAD

**Issue by Freezeraid** [Eastrall/Rhisis#284]
- First, You can't equip an item if :
                - This is the FIRST TIME you wanna EQUIP it since you're log
                - AND the DESTINATION SLOT is basically EMPTY when you log in
                In fact the item is changing slotId so it's equiped. indeed, it's equiped when you de-log and re-log, so it's saved on the DB.

- Second, after playing with this bug, I was able to bug the DB Load of my inventory when I log in. For exemple, some items were equiped in my DB, and I saw those items equiped in the Character selection. But in game, I can't found thoses items anywhere.

**Comment by Eastrall** [comment]
I have been able to reproduce the bug. Thank you for your feedback. I'm going to look into the `InventorySystem` and check what's wrong.
I'll keep you updated.

**Comment by Eastrall** [comment]
It should be fixed with PR #336
