### ISSUE TITLE
Range normal attack has no damage

### ISSUE THREAD

**Issue by ghost** [Eastrall/Rhisis#286]
![image](https://user-images.githubusercontent.com/10215125/69900653-2179f000-13b1-11ea-8d9d-03fe4efa07e5.png)

**Comment by Eastrall** [comment]
Indeed, this feature is not implemented yet, because the job system and job changer is not really completed. It will be added when the quest system and job system will be fully operationnal.

**Comment by SvenLlama** [comment]
This one was fixed a while ago, can be closed I think.

**Comment by Eastrall** [comment]
You are correct. Closing.
