### ISSUE TITLE
Rewrite summaries for packet structures.

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#291]
@Kaev developped a tool that parses the comment summaries of the packets and creates a Wiki documentation of implemented packets.

Some packet summaries need a rewrite so it can be well documented.

For example:
https://github.com/Eastrall/Rhisis/blob/644d0a0e82ac107b8b472a261eacd90cc0e0e226/src/Rhisis.Network/Packets/World/ChangeJobPacket.cs#L6-L10

This line should be rewrite to indicate a more explicit message:

> Packet sent to change the player's job.

We **should** avoid `<cref=""/>` tags that causes issues with the XML parser.

**Comment by Kaev** [comment]
You can use cref Tags, i just have to parse differently then. I don't think we need a cref on the same class though.

**Comment by Eastrall** [comment]
I agree. We should explain explicitly what the packet is.
