### ISSUE TITLE
Lower capital table names for a better compatibility with all platforms

### ISSUE THREAD

**Issue by tekinomikata** [Eastrall/Rhisis#296]
Eastrall found the issue to be related to https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/526 which was indeed the case.

I've posted a suggestion so we would change the EF table attributes to use lower capital naming as well as updating the migrations to reflect the same, so we would attain a better compatibility with other OS and avoid having to use different settings to be able to run under other platforms or users having issues with the same.

https://discordapp.com/channels/294405146300121088/599534604453412865/668136336984637496

**Comment by Eastrall** [comment]
I think this could be a good idea. Can you fix the table names and regenerate the a clean migration from scratch ? I suggest you to delete the "Migration" folder and create a new one named "InitialMigration".

**Comment by tekinomikata** [comment]
@Eastrall Will do!

**Comment by Eastrall** [comment]
Merged with PR #297
