### ISSUE TITLE
Create new systems

### ISSUE THREAD

**Issue by tekinomikata** [Eastrall/Rhisis#321]
Will post here if I find anything else as I am still reading and using the guide myself.

In regards https://github.com/Eastrall/Rhisis/wiki/Create-new-systems

1. `Note: All packet header are located in Rhisis.Core/Network/Packets/PacketType.cs.` should be `Rhisis.Network/Packets/PacketType.cs.`

2. Remove `this` keyword from the create new system, last 3 code blocks and `this.Message = packet.Read<string>();` have it.

**Comment by Eastrall** [comment]
Thanks for the feedback! The docs have been updated.
