### ISSUE TITLE
Handle a list of created players in the DB at the cluster's launch and update it when a player is created or deleted

### ISSUE THREAD

**Issue by Freezeraid** [Eastrall/Rhisis#326]
Would be useful to know if a player exists in the DB without having to ask the DB directly
ex : /say system

**Comment by tekinomikata** [comment]
that should be on the cluster, because if you have multiple servers that wouldn't be accurate.

**Comment by Freezeraid** [comment]
Indeed !

**Comment by Eastrall** [comment]
Implemented in PR #490
You can now query the cache to check if the player exists. Just inject the `IPlayerCache` interface in your chat commands, handlers or systems to access the player cache. The call the `IPlayerCache.Get(player.CharacterId)` method to retrieve the wanted player. If the player doesn't exists in the cache, it will be loaded from the database in added to the cache.
