### ISSUE TITLE
Create a Update command to rhisis-cli database to avoid having to wipe the tables every build

### ISSUE THREAD

**Issue by tekinomikata** [Eastrall/Rhisis#327]
Have a `rhisis-cli database update` command that will apply migration updates only without having to wipe the whole database every time.

**Comment by Eastrall** [comment]
There is actually a `rhisis-cli database update` command that does the job: https://github.com/Eastrall/Rhisis/blob/develop/src/Rhisis.CLI/Commands/Database/DatabaseUpdateCommand.cs#L57

The thing is, we need to be careful and commit only valid migration and not intermediary dev migrations. So we have to discuss about the database/table structure before any developments impacting the database.
