### ISSUE TITLE
Rhisis database initialize crashes the batch script

### ISSUE THREAD

**Issue by Freezeraid** [Eastrall/Rhisis#334]
After asking for informations, the program is creating the database structure and then crashes instantly at this point :

![image](https://user-images.githubusercontent.com/16978010/75463979-d73fe500-5986-11ea-82c9-1a6562c2f1ec.png)

It says : "Failed to open the referenced table 'characters'"

**Comment by Eastrall** [comment]
Fixed. Can you try again ?

**Comment by Eastrall** [comment]
Any news about this issue @Freezeraid ?

**Comment by Freezeraid** [comment]
Ok, I re-test and I don't know why but the issue is gone. Seems that it was only for me.

**Comment by Eastrall** [comment]
Thanks for the feedback. I guess it's solved then. 😄
