### ISSUE TITLE
Items database structure improvements

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#341]
The actual database model for items and character inventory is pretty simple. Everything is located in a simple table named `Items`. This table contains everything related to the items and inventory. (Slot, Quantity, bonuses, etc...)

This structure has some issues when we start to deal with systems like the `MailSystem` or the `BankSystem` since the `Items` table is only for **inventory items**.

The database structure needs to be changed for a better structure to support all sytems related to items. This is what I propose:
### Remove all non-essential columns from `Items`

`Items` table needs to be more general

### Introduce a general "storage" table that will have the following columns:

| Column Name | Column Type | Comment |
| ----------------|----------------|-------------|
| `CharacterId`   | `INT` | Every item storage will be linked to a character |
| `StorateTypeId` | `INT` | A storage will have a type, that could be : Inventory, Bank or extra bag |
| `ItemId` | `INT` | This is a foreign key to the item that lives in the general `Items` table. |
| `Slot` | `SMALLINT` or `TINYINT` | This is the slot of the item in the storage container. |
| `Quantity` | `SMALLINT` or `INT` | The item quantity. |
| `Updated` | `DATETIME` | The last time the item was updated. (changed slot, increase/decrease quantity, change owner, etc... |
| `Status` | `TINYINT` | For now it will contain the status: `Active` or `Deleted`. But in the future, we could have more statuses. |

### Item attributes

In the future, with the weapon awekening system, items/weapons will have attributes like `+3 DEX` or `-6% Speed`. In order to prepare for such system, we need to add some extra tables to the database to link an item to multiple attributes.

### Introduce an `Attributes` table

This table will contain all the attributes of the `DefineAttributes` enum. We will seed the table using the `Entity Framework Core` `HasValues()` method during a migration.
The table will only contain 2 columns:

| Column Name | Column Type | Comment |
| ----------------|----------------|-------------|
| `Id` | `INT` | The attribute id |
| `Name` | `VARCHAR(20)` | The attribute name |

### Introduce an `ItmeAttributes` table

This table will be used as a many to many table between items and attributes.
One Item can have multiple attributes.
One attribute can be linked to multiple items but with different bonuses.

| Column Name | Column Type | Comment |
| ----------------|----------------|-------------|
| `ItemId` | `INT` | Foreign key to the `Items` table and `Id` column. |
| `AttributeId` | `INT` | Foreign key to the `Attributes` table and `Id` column. |
| `Value` | `INT` | Attribute value. |

*Also, we could consider adding an extra field that describes the if the value is a percentage or a numeric value*

## Database schema

With this, we are pretty good for other systems like Mail or Bank systems. In the end, the database structure will kinda look like the following schema:

![image](https://user-images.githubusercontent.com/4021025/83348134-0cfbbd80-a32a-11ea-8f86-9620d706a353.png)

---

This solution can be good, because it decoralates the items from the inventory, bank or mails. Queries will also be simple enough like:
```sql
SELECT * FROM Items i
LEFT JOIN ItemAttributes ia ON i.Id = ia.ItemId
WHERE i.Id = 42;
```
On the other hand, if we want to query all items of a character:
```sql
SELECT * FROM ItemStoarge storage
LEFT JOIN Characters c ON storage.CharacterId = c.Id
LEFT JOIN Items i ON storage.ItemId = i.Id
LEFT JOIN ItemAttributes ia ON i.Id = ia.ItemId
WHERE c.Id = 42 AND storage.StorageTypeId = 1
```
---
Any thoughts or other ideas about this improvements?

**Comment by MarkWilds** [comment]
Should BankItem not also have a quantity?
And shouldn't mail have a message (string) and a many to many relation towards an item?
**Mails**
id
recepientId
senderId
message
goldAmount

**MailItems**
mailId
itemId
quantity

**Comment by Eastrall** [comment]
Yes, `BankItem`s will also have a quantity field.
The schema I've exposed on the origial post was to share an idea I had to have multiple tables to manage items instead of one with "everything" inside; like it is today. Thus, this schema is not complete at all.

I don't think it's necessary to have a Many To Many relation ship since you can only attach one item to a mail.
![image](https://user-images.githubusercontent.com/4021025/80346005-5740d900-886a-11ea-9957-cd0c664d5b17.png)
More information here: http://flyff-wiki.webzen.com/wiki/Mail_System

**Comment by MarkWilds** [comment]
I know it was just a draft, sorry if I sounded a bit definitive on this matter.

Oh makes sense, I was assuming something like this (only one item).

**Comment by Eastrall** [comment]
I have reworked the previous database schema proposition and made a new schema. This new schema introduces a new `Attributes` table that will be seeded with the `DefineAttributes` value for data integrity and I've added a many to many relation ship between `Items` and `Attributes` tables.

The real attributes value will be stored in that join table: `ItemAttributes`.

Schema is open to discussion of course.

**Comment by MarkWilds** [comment]
whats the goal/use of these attributes?

**Comment by Eastrall** [comment]
These attributes will be used in the future weapon awekening system: http://flyff-wiki.webzen.com/wiki/Awakening
One weapon/armor/jewels can have multiple bonuses such as +4 STR or -6% speed.

**Comment by Eastrall** [comment]
There's an image of how awakened weapons look like in game:

![image](https://user-images.githubusercontent.com/4021025/82726219-ce8b5080-9ce2-11ea-92d1-da7ae47d2eba.png)

**Comment by Eastrall** [comment]
Original issue updated with new database schema and idea.
