### ISSUE TITLE
Improve ISC communication system

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#350]
The FLYFF infrastructure has been built around the a Cluster and Channel system. This means that a single server can have multiple channels.
For example, a server called `Rhisis` can have two channels named `Channel 1` and `Channel 2`.
When a player connects to `Channel 1` it every other players connected to the same channel. 

The cluster has an important role in data centralization of each channels. Like keep a list of connected players and in which channel they are currently playing. Sometimes, when a player makes an action on a channel, the action **MUST** be replicated on the other channels. 
In other words, a channel should be able to broadcast a message to one, multiple or all channels of a cluster.

## The actual system

In the Rhisis context, the **Server** is the `ClusterServer` and the **Channel** is the `WorldServer`.
An Inter-Server Communication system (**ISC**) already exists in the Rhisis project. It is really simple and does the job. But I believe we can do something better.
At the moment, the ISC structure looks like:
![image](https://user-images.githubusercontent.com/4021025/80117504-8fed6380-8587-11ea-81f1-6ffdaeaf17bc.png)

Here, we centralize everything on the `Login Server` that is responsible for handling incoming player authentications. But also has a `Core Server` orignaly made to centralize the server management and broadcast system.
This has been made to centralize the cluster and channel list that will be sent to a new player when it connects to the `Login Server`.
So, when the a `WorldServer` starts, it connects to the `CoreServer` and will appear in the graphic client's server/channel list.

This has a heavy drawback, FLYFF can display many clusters. So when it comes to broadcast messages from a world server to its cluster, it will have to send the message to the `CoreServer` and the broadcast to every channels. If we have X clusters with Y channels and each one of them has N players that send a request to the `CoreServer`, the server will just blow up.

## The improved system idea

The idea of the new version is to centralize every cluster specific actions in the `ClusterServer` project. Just like the `LoginServer` along with the `CoreServer`, the `ClusterServer` will also have a second server running on the same application.

This will result on a the following schema:

![image](https://user-images.githubusercontent.com/4021025/80124750-03e03980-8591-11ea-8045-56a607a6280b.png)

The `WorldServer`s (channels) will now connect to its parent `ClusterServer` instead of connecting the `CoreServer` present on the `LoginServer`.
This will allow to reduce the responsability of the `Login/Core Server` and each `ClusterServer` will have to handle its N `WorldServer`s (channels) connected. When a `WorldServer` needs to broadcast a message to all servers in the cluster, it sends the message to the `ClusterServer` which will have the responsability to broadcast the message to every channel connected.

## Another Idea

As @MarkWilds mentionned, another approach would be to extract the `CoreServer` from the `LoginServer`. This will help to decouple the tasks and will centralize the ISC system.

![image](https://user-images.githubusercontent.com/4021025/80576074-dc5ff580-8a04-11ea-9036-5d471880b063.png)

The idea is like the previous one, but with an extra server.

## Roadmap

To be added

**Comment by MarkWilds** [comment]
I am willing to take this on! Can you assign me to this?

**Comment by Eastrall** [comment]
Sure! Thanks.

**Comment by MarkWilds** [comment]
As an extension to this "issue"; in the future we might want to decouple the core from login and allow multiple login servers.

Login *--> core <--* Cluster <--* World

**Comment by Eastrall** [comment]
Original post update with @MarkWilds idea. 😉

**Comment by MarkWilds** [comment]
1. What should happen when a cluster server crashes or is unavailable when other servers are running?

The cluster is currently responsible for caching a list of available worlds and initial character handling:
- Gets/sends character list for cluster.
- Create character
- Delete character
- Prepare to join world

To me it seems the cluster has no impact(currently) on ingame play for clients connected to the world servers.
So if a cluster becomes unavailable you cannot join it (not that of a big deal to me).

But the cluster should be able to be started up again an re-authenticate with the core and have the worlds reconnect?

2. What should happen when the core server crashes or is unavailable when other servers are running? (new core server without authentication functionality)

The core is responsible for caching a list of clusters with it's worlds and for higher up ISC between clusters and worlds.
When the core is unavailable and other servers are running clients cannot login and ISC between clusters cannot happen.

What should happen when other servers are running (clusters, worlds) and the cluster is unavailable but the sysadmin wants to restart it. How do we handle this?

**Comment by Eastrall** [comment]
> What should happen when a cluster server crashes or is unavailable when other servers are running?

I think in the actual servers, when the cluster crashes, every player is disconnected from the channels. In my opinion, it does impact the channels and in game experience. Let's say that you want to send a private message to a player that is on another channel, you will send the request to the `ClusterServer` that will forward to the player in the correct world server / channel. But if the `ClusterServer` is down, the message will never arrive.

If the `Cluster Server` crashes, the hosting system should be able to restart it automatically (using a deamon on Linux or service on Windows), and then as you said, reauthenticate to the `CoreServer`. But the `WorldServer`s should also reconnect to the cluster. `Sylver.Network` has a retry mecanism that could be useful in this case.

Finally, for the messages that are sent when the Cluster is down, maybe we could setup a packet queue instead of sending them right way?

Now we need to decide what's the best solution :
1. We disconnect every player of each channels in the cluster
2. We keep the players connected and queue the packets that should be sent to the cluster.

> What should happen when the core server crashes or is unavailable when other servers are running? (new core server without authentication functionality)

As you said, the `Core Server` is responsible to cache the clusters and channels list and send them to the `Login Server`, so when a new client connects, it will receive the available servers and channels list.
If the `CoreServer` crashes, I don't think it's mandatory to disconnect every player of each clusters and channels. Simply, the `Login Server` available server's list will not be updated as long as the Core Server is down.

**Comment by MarkWilds** [comment]
> In my opinion, it does impact the channels and in game experience.
If channel overlapping features are currently implemented like whispers, etc.. this is indeed correct.
I was under the assumption they weren't currently. But still we need to look at the future ofcourse.

> Finally, for the messages that are sent when the Cluster is down, maybe we could setup a packet queue instead of sending them right way?
I wouldn't queue the messages as this seems as a critical (exceptional) situation and needs to be solved asap by sys admins. As long as the cluster is down it wont be able to provide the services to worlds and this will reflect ingame(probably? this is very dependent opon how the client is working).
Like when chat is down in alot of mmo's you can still keep playing but cant chat or send mail.

**Comment by MarkWilds** [comment]
I want to suggest to finish this issue with what we have now and create a new issue stating the decoupling of login and core.

**Comment by Eastrall** [comment]
Sounds good to me. I'll open a new issue for decoupling then.

**Comment by MarkWilds** [comment]
This one can be closed

**Comment by Eastrall** [comment]
Solved with PR #355.
Closing.
