### ISSUE TITLE
Broken jump animation

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#362]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior

When walking with "W" and jumping at the same time, the player should jump foward.

## Current Behavior
The player jumps, but the walking animation stops.

## Steps to Reproduce

1. Walk using the W key
2. Press space bar to jump

**Comment by Freezeraid** [comment]
Even moving forward with the mouse then jump stops the movement

**Comment by YoniSL** [comment]
This may be related to movement in general, simply walkign with W also lacks proper animation as it seems the character stops walking often. as if the location gets updated forcefully.

https://files.catbox.moe/xp42ia.mp4 see video
