### ISSUE TITLE
"User ID already exists" error

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#367]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Item is purchased from the shop.

## Current Behavior
Buying blinkwings **with the value of 1** from [Magic] Marche gives "User ID already exists" message box.
![mZpLpx5](https://user-images.githubusercontent.com/65497193/82152452-20eaee00-9859-11ea-9c1d-2be78fc9acab.jpg)

## Steps to Reproduce
1. Drag blinkwing into your inventory.
2. "User ID already exists" Message box appears.

**Comment by Eastrall** [comment]
This error occurs when an item has a cost of 0 or negative. The client error isn't explicit.

**Comment by Eastrall** [comment]
Fixed in #382
