### ISSUE TITLE
Cannot sell items

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#369]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Item is sold to the NPC.

## Current Behavior
Cannot sell the item.
![11](https://user-images.githubusercontent.com/65497193/82154247-7a0c4f00-9864-11ea-998b-f33488bf4059.jpg)

## Steps to Reproduce
1. Drag item into the NPC Shop window.
2. "Please unequip the item before selling it." is displayed.

**Comment by Eastrall** [comment]
Fixed with the item container rework done with PR #392
