### ISSUE TITLE
Broken Motions/Emoticons

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#370]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Player should sit down or teleport to nearest town.
Emoticon should display above player head.

## Current Behavior
Clicking Sit Down and Nearest Town Teleport in the Motion window does nothing.
Clicking any of the emoticons in the Motion window does nothing.

## Steps to Reproduce
1. Click Sit Down or Nearest Town Teleport.
2. Click any of the Emoticons.

**Comment by Eastrall** [comment]
Related to Motion system #82

**Comment by Eastrall** [comment]
FIxed #82
