### ISSUE TITLE
Sold items return after relogging

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#371]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Items sold for penya should be saved after relogging.

## Current Behavior
Items that are sold, reappear in the inventory after relogging but only the created penya is saved.

## Steps to Reproduce
1. Sell items to the NPC.
2. Relog.
3. Check inventory.

**Comment by Eastrall** [comment]
Fixed with the item container rework done with PR #392
