### ISSUE TITLE
Character Screen - Player wields 2 swords

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#373]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Vagrant class player is shown to be holding 1 sword.

## Current Behavior
Player is wielding 2 swords in both hands.
![21](https://user-images.githubusercontent.com/65497193/82155304-e50d5400-986b-11ea-8d78-d1e17e5978b9.jpg)

## Steps to Reproduce
1. Login.
2. Reach the Character window.

**Comment by Eastrall** [comment]
This might be related to issue #372. Since there are two items at the same slot the cluster server displays the two swords.
