### ISSUE TITLE
Client won't start after crash

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#377]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Client starts.

## Current Behavior
Client hangs, then crashes before the login screen.

## Steps to Reproduce
1. Click NPC Isruel (or any NPC capable of crashing you).
2. Attempt to restart the client.. which crashes.
3. Delete neuz.ini
4. Client will now start again.

**Comment by Eastrall** [comment]
Fixed with PR #375 . The problem was due to a bad serialization of name on server side.
