### ISSUE TITLE
Changing armour does not always update

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#386]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Armour is equipped and unequipped.

## Current Behavior
Player is either naked, or the switched armour doesn't update for the client.

## Steps to Reproduce
1. Equip armour dropped from mobs.
2. Relog and it will then update.
**Coincidentally, sometimes you can't reconnect to the game after this bug happens.**

**Comment by Eastrall** [comment]
Fixed with the item container rework done with PR #392
