### ISSUE TITLE
Stat Points don't reset after job change quest

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#404]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Stat points reset after completing 1st job change quest.

## Current Behavior
Old stats applied as Vagrant do not reset after completing the quest.

## Steps to Reproduce
1. Reach level 15.
2. Complete job change quest.
3. Check H.

**Comment by Eastrall** [comment]
I have begun the restat system when the job change quest is completed. I've added 2 new entries to the quest scripts in the `rewards` section :
```lua
QUEST_XXX = {
        ...
	rewards = {
		restat = true,
		reskill = true
	}
}
``` 
By setting `restat` to `true`, when the player completes the quest, its stats will be reseted to 15 by default. Same goes for `reskill`.

**Comment by Eastrall** [comment]
Also added the possibility add give extra skill points as rewards:
```lua
QUEST_XXX = {
        ...
	rewards = {
		skillPoints = 40
	}
}
```
