### ISSUE TITLE
Blinkwing while trading crashes

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#405]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Open trade/shop windows automatically close after teleporting.

## Current Behavior
Game crashes. Can't launch without deleting neuz.ini

## Steps to Reproduce
1. Use a Blinkwing.
2. Quickly open a shop NPC.
3. Wait until teleport (crash).

**Comment by Eastrall** [comment]
I am not able to reproduce this issue on the server.
When I use the blinkwing and open a shop, it interupts the blinkwing usage.

**Comment by sodamnfake** [comment]
Here is another way to reproduce it: Place a blinkwing on the hotbar. Trade with [Magic] Marche and then press F1 - 9 (whatever key you put it on).

**Comment by Eastrall** [comment]
Ok, I've been able to reproduce the issue. I can investigate. Thanks for reporting!
