### ISSUE TITLE
Player can't de-level

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#413]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Player can lose a level if close enough to 0% exp.

## Current Behavior
Exp won't change, or freezes at a certain point after dying.

## Steps to Reproduce
1. Level up.
2. Die.

**Comment by Eastrall** [comment]
Can you give me more details about your character level?
From what I remember, you loose exp when you die, only when you are level 20+.

**Comment by sodamnfake** [comment]
16. If this is true then my report isn't valid. Just found the answer here: http://flyff-wiki.webzen.com/wiki/Death

**Comment by Eastrall** [comment]
According to this table and your level, you shouldn't have any penality:

Character Lv. | Experience Penalty
-- | --
1 ~ 20 | No penalty
21 ~ 29 | 6% Exp. Loss
30 ~ 59 | 5% Exp. Loss
60 ~ 89 | 4% Exp. Loss
90 ~ 99 | 3% Exp. Loss
100 ~ 109 | 2% Exp. Loss
110 ~ 120 | 1.5% Exp. Loss

Can we close this issue then?
