### ISSUE TITLE
Can't equip arrows

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#415]
# :beetle: Bug Report

**Rhisis version: v0.4.3** 

## Expected Behavior
Acrobat can equip arrows.

## Current Behavior
Acrobat cannot equip arrows, however, this bug is not 100% reproducible.

## Steps to Reproduce
1. Equip bow.
2. Try to equip arrows.

**Comment by Eastrall** [comment]
It also seems that it's not only related to arrows and might be related to every equipable items. Hats, gloves, etc... This needs an investigation.

**Comment by reeeccoo** [comment]
I also experienced this with a shield and head item. Issue was fixed with a relog.
