### ISSUE TITLE
Food item isnt visible in inventory after purchase

### ISSUE THREAD

**Issue by reeeccoo** [Eastrall/Rhisis#417]
# :beetle: Bug Report

**Rhisis version:** 0.4.3 

## Expected Behavior

The item should be visible in the inventory.

## Current Behavior

The space is occupied, however the item isn't visible until a relog is made.

## Steps to Reproduce

1. Trade Losha.
2. Buy 50 Lollipops.

**Comment by Eastrall** [comment]
Thanks for reporting this issue.
This might be a bug with the inventory serialization when you log-in. As you mentionned, a simple disconnect then reconnect makes the items appear, which means that the items are really there and saved into the database.

I'm currently working on a similar inventory issue, also related to #415
