### ISSUE TITLE
Hotbar items disappear/reappear

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#420]
# :beetle: Bug Report

**Rhisis version:** v0.4.3

## Expected Behavior
Items placed on the hotbar remain unless removed.

## Current Behavior
Items placed on the hotbar can randomly disappear and reappear after dying or relogging.
Upon death, random items in your inventory can replace the item on your hotbar.
They can also **reappear** after manually removing from the hotbar.

## Steps to Reproduce
1. Place or remove any item on the hotbar.
2. Die or relog (not 100% reproducible).

**Comment by Eastrall** [comment]
Solved with PR #431
