### ISSUE TITLE
Ranged, loud sounds

### ISSUE THREAD

**Issue by sodamnfake** [Eastrall/Rhisis#429]
# :beetle: Bug Report

**Rhisis version:** v0.4.x

## Expected Behavior
Sounds are only played within expected range and volume.

## Current Behavior
Sounds produced from mobs can be heard at a far distance.
Also at Eron's Factory 1 & 2, you can hear very loud doors, fans and stuff.

## Steps to Reproduce
1. Go near any area that has mobs.
2. Go to Eron's Factory 1 or 2.
3. Listen.

**Comment by Eastrall** [comment]
From what I understand, this can be related to the client. But maybe there is an extra configuration to apply on the server side in order to reduce listening range.
I'll investigate this.
