### ISSUE TITLE
New characters are created as Mercenary (1) instead of Vagrant (0)

### ISSUE THREAD

**Issue by SvenLlama** [Eastrall/Rhisis#477]
I tried changing:
            builder.Property(x => x.JobId).IsRequired().HasColumnType("TINYINT").HasDefaultValue(1);
to
            builder.Property(x => x.JobId).IsRequired().HasColumnType("TINYINT").HasDefaultValue(0);
and
            builder.Property(x => x.JobId).HasColumnType("TINYINT").HasDefaultValue(0);

in CharacterConfiguration.cs but still the database characters entry got value 1
Also tried using the cli cmd "database update" but this didn't change anything either.

Still before the Db.SaveChanges() the DbCharacter#JobID is 0, but after it is 1.

**Comment by Eastrall** [comment]
This is a weird behavior. The character creation in the `ClusterServer` sets the `JobId` to 0 (L.141):
https://github.com/Eastrall/Rhisis/blob/31f96ab5bdbb017ec696510221fa3009c2c0ebbd/src/Rhisis.Cluster/Handlers/CharacterHandler.cs#L130-L141

As for the database configuration, there is indeed an error here:
https://github.com/Eastrall/Rhisis/blob/31f96ab5bdbb017ec696510221fa3009c2c0ebbd/src/Rhisis.Database/Entities/Configuration/CharacterConfiguration.cs#L17
and should be changed to 0. And to apply this change to the database, a new migration should be generated and applied to the database.

**Comment by Eastrall** [comment]
Fixed in #487
