### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by HanCouple** [Eastrall/Rhisis#498]
# :beetle: Bug Report

**Rhisis version:** 

## Expected Behavior

I followed the setup guide successfully sofar, up to the point of the server configuration. 
The "dotnet build" command worked. Now im trying to cofigure the server using the "rhisis-cli" commands.

## Current Behavior

My command prompt is giving me the error "Error: rhisis-cli is not a command" (I´ve tried to run this with multiple commands / also, yes im using the command prompt as admin).

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

I´m running this all on a windows 10 os. If anyone has any ideas on how to fix it please let me know.
Thanks in advance, also for uploading this project, i really appreciate it.

**Comment by Eastrall** [comment]
Hi, from where are you starting the `rhisis-cli` command ? You need to be inside the `bin/` folder and start `rhisis-cli` or `rhisis-cli.bat`.
