### ISSUE TITLE
Disallow username duplicate in Users table

### ISSUE THREAD

**Issue by Steve-Nzr** [Eastrall/Rhisis#56]
Actually, we can have two person with the same username/password.

_ToDo_:
- [x]  Add a unique key on __Username__ field

**Comment by Eastrall** [comment]
We need to define a username policy too. For exemple, do we accept usernames like "admin" and "Admin" ?
Is it the same account ?

**Comment by Steve-Nzr** [comment]
I think we could use the UNIQUE KEY policy with the SQL provider. According to our Encoding (UTF-8), it will be case sensitive or not.

**Comment by CineXMike** [comment]
UTF-8 is more than enough is this case, good call @Steve-Nzr

**Comment by Eastrall** [comment]
Fixed in PR #185
